### ISSUE TITLE
How would smr handle discrete values? 

### ISSUE THREAD

**Issue by The18thWarrior** [omphalos/smr#6]
I'm plugging in a y that's a vector of binary values [0,1,0,0]. The algorithm is giving me answers in that format, but I can't tell if it's correct (if it was built to handle those kinds of problems).

**Comment by omphalos** [comment]
@The18thWarrior there's no special logic around binary values.  I don't see why you can't use it to form predictions for binary data however.  You may want to round the hypothesis, depending on what you're doing.  `smr` doesn't provide an error measurement function, but you ought to be able to calculate error according to some metric to get an idea of how well the algorithm works with your data.

**Comment by omphalos** [comment]
@The18thWarrior I'm going to close this issue.  If you have more questions feel free to post them.
