### ISSUE TITLE
SMR calculting the wrong result

### ISSUE THREAD

**Issue by dean-vollebregt** [omphalos/smr#7]
const smr = require('smr');

let regression = new smr.Regression({ numX: 3, numY: 1 })

regression.push({ x: [1, 2, 7], y: [159] });
regression.push({ x: [1, 1, 5], y: [160] });
regression.push({ x: [1, 1, 5], y: [175] });
regression.push({ x: [0, 1, 3], y: [200] });
regression.push({ x: [0, 4, 7], y: [160] });
regression.push({ x: [1, 1, 4], y: [130] });
regression.push({ x: [0, 2, 3], y: [152] });
regression.push({ x: [0, 1, 5], y: [160] });
regression.push({ x: [0, 1, 4], y: [100] });
regression.push({ x: [0, 1, 3], y: [140] });
regression.push({ x: [0, 2, 7], y: [159] });
regression.push({ x: [1, 1, 3], y: [220] });

console.log(regression.hypothesize({ x: [1, 2, 7]}));    => [ 229.29673135852903 ]
Using a statistics package the equation is 
Y = 163.7 + (21.92)X1 + (9.306)X2 + (-5.838)X3       => 163.4

please fix your package

**Comment by omphalos** [comment]
@dean-vollebregt there are different kinds of regression, which use different algorithms and yield different results.  I guess this explains the difference you're seeing.

The regression algorithm in this repo is similar to the [regression code](https://rosettacode.org/wiki/Multiple_regression) at rosetta code.  The rosetta code for regression is kind of all over the place but I have collected it in a github repo for easier viewing: https://github.com/omphalos/rosettacode-js-regression.  For your sample, the output from rosettacode-js-regression corresponds to the output from smr:

```js
var data = [
  { x: [1, 2, 7], y: [159] },
  { x: [1, 1, 5], y: [160] },
  { x: [1, 1, 5], y: [175] },
  { x: [0, 1, 3], y: [200] },
  { x: [0, 4, 7], y: [160] },
  { x: [1, 1, 4], y: [130] },
  { x: [0, 2, 3], y: [152] },
  { x: [0, 1, 5], y: [160] },
  { x: [0, 1, 4], y: [100] },
  { x: [0, 1, 3], y: [140] },
  { x: [0, 2, 7], y: [159] },
  { x: [1, 1, 3], y: [220] }
];

var y = new Matrix(data.map(d => d.y))
var x = new Matrix(data.map(d => d.x))

console.log(y.regression_coefficients(x))

//  [ [ 43.16036772216564 ],
//  [ 11.647599591419926 ],
//  [ 23.26302349336054 ] ]
```

If you call `regression.calculateCoefficients()` on your smr example you should see the same values (less floating point precision issues).

**Comment by omphalos** [comment]
@dean-vollebregt I'm going to close this issue.  Hopefully my explanation addressed your concerns.  In case it didn't, and think I can help, feel free to reopen this issue with more detail.
